image: node:12.17.0 # or whatever version of node you are on

cache:
  paths:
    - core/node_modules/

pages:
  stage: deploy
  # Required artifact for GitLab Pages
  artifacts:
    paths:
      - core/public
