image: node:12.17.0 # or whatever version of node you are on

cache:
  paths:
    - core/node_modules/

pages:
  stage: deploy
  script:
    - cd core
    - npm install
    - npm run build
    - npm run build-storybook
  # Required artifact for GitLab Pages
  artifacts:
    paths:
      - public
